### ISSUE TITLE
cannot install 1.2 via pypi by specifying version

### ISSUE THREAD

**Issue by privateip** [arista-eosplus/ztpserver#273]
pip install ztpserver==1.2.0
Downloading/unpacking ztpserver==1.2.0
  Could not find a version that satisfies the requirement ztpserver==1.2.0 (from versions: 1.0.0, 1.1.0, 1.1.1)
Cleaning up...
No distributions matching the version for ztpserver==1.2.0

**Comment by advornic** [comment]
Yup, this is because of this line in setup.py:

    download_url='https://github.com/arista-eosplus/ztpserver/tarball/v1.1.0',

We need to fix it an re-upload the file to pypi.

**Comment by advornic** [comment]
Ok this is fixed - will raise separate issue for enhancements to the way we deal with versions and releases.
