### ISSUE TITLE
ztpserver.wsgi - "TypeError: start_wsgiapp() takes no arguments (1 given)"

### ISSUE THREAD

**Issue by phil-arista** [arista-eosplus/ztpserver#282]
While testing the ZTPServer as a wsgi app under Apache 2.4 on RHEL6 I ran into the following issue where the app cannot be loaded:

The function below in app.py looks like no args are defined, but we pass in 1+ args in ztpserver.wsgi. Is this something that just needs a simple update?

https://github.com/arista-eosplus/ztpserver/blob/27d93ae1118fc1830562787ac0a762d7205388db/ztpserver/app.py#L99

```
[Wed Jan 28 09:07:39.857286 2015] [:error] [pid 1944] [remote ::1:216] mod_wsgi (pid=1944): Target WSGI script '/etc/ztpserver/ztpserver.wsgi' cannot be loaded as Python module.
[Wed Jan 28 09:07:39.857329 2015] [:error] [pid 1944] [remote ::1:216] mod_wsgi (pid=1944): Exception occurred processing WSGI script '/etc/ztpserver/ztpserver.wsgi'.
[Wed Jan 28 09:07:39.857396 2015] [:error] [pid 1944] [remote ::1:216] Traceback (most recent call last):
[Wed Jan 28 09:07:39.857438 2015] [:error] [pid 1944] [remote ::1:216]   File "/etc/ztpserver/ztpserver.wsgi", line 43, in <module>
[Wed Jan 28 09:07:39.857541 2015] [:error] [pid 1944] [remote ::1:216]     application = start_wsgiapp(conf)
[Wed Jan 28 09:07:39.857584 2015] [:error] [pid 1944] [remote ::1:216] TypeError: start_wsgiapp() takes no arguments (1 given)
```

**Comment by phil-arista** [comment]
Just adding "conf" as an argument fixes the issue.  Now just trying to find the logs that ztpserver outputs.  They don't seem to be in the usual place: /opt/rh/httpd24/root/etc/httpd/logs/error_log

**Comment by advornic** [comment]
I think that change won't add any value - the correct fix seems to me the other way round:

<pre>
import sys

from ztpserver.app import start_wsgiapp

-conf = '/etc/ztpserver/ztpserver.conf'

sys.stdout.write('Starting ZTPServer')
-sys.stdout.write('using config file %s' % conf)

-application = start_wsgiapp(conf)
+application = start_wsgiapp(conf)
</pre>

**Comment by advornic** [comment]
Fixed in development.
