### ISSUE TITLE
Using lldp instead of serial number or mac address for turning on ZTP with Arista switches.

### ISSUE THREAD

**Issue by rnilekani** [arista-eosplus/ztpserver#317]
Is there a documentation around zero touch provisioning with LLDP? We have tested ZTP successfully with mac addresses and serial numbers but would prefer an alternative/feasible approach to bring up machines into production. Any thoughts or ideas would be greatly appreciated.

**Comment by phil-arista** [comment]
Hello,
Have you seen the main docs at http://ztpserver.readthedocs.org ? We also have a cookbook with some basic recipes like this: http://ztpserver.readthedocs.org/en/master/cookbook/dynamicNodes.html

**Comment by rnilekani** [comment]
Thanks, Phil. I shall give that a shot. Its nice to see these cookbooks in place.

**Comment by phil-arista** [comment]
Great! The basic idea is to use neighbordb (usually located at /usr/share/ztpserver/) to link interface patterns to definitions. Let us know if you hit any snags or need some pointers.
