### ISSUE TITLE
Problems starting ZTPS application on ZTPS Fedora Demo

### ISSUE THREAD

**Issue by privateip** [arista-eosplus/ztpserver#318]
**copy and pasted from arista-eosplus/ansible-eos issue 44**

When I attempt to start ZTPS by typing ZTPS I get the following error:

File "/bin/ztps", line 4, in 
import pkg_resources
File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2793, in 
working_set.require(requires)
File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 673, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: mock

I have installed mock but this hasn't fixed it.

**Comment by phil-arista** [comment]
Looks like during pip install mock is throwing error:

```
Downloading/unpacking mock (from ztpserver==1.3.2)
  Running setup.py egg_info for package mock
    mock requires setuptools>=17.1. Aborting installation
    Complete output from command python setup.py egg_info:
    mock requires setuptools>=17.1. Aborting installation
```

@advornic Have you taken a look at this one yet?

**Comment by phil-arista** [comment]
Looks like an issue with Mock as seen here https://github.com/testing-cabal/mock/issues/261

**Comment by phil-arista** [comment]
@mprior1 - We know what is causing this and will release a new version today to address it. In the mean time, you can resolve this by:

1. cd /home/ztpsadmin/ztpserver
2. vi requirements.txt
remove the line that has 'mock'
save file (:wq)
3. python setup.py build # with sudo depending on which user you logged in with
4. python setup.py install # with sudo depending on which user you logged in with
