### ISSUE TITLE
distutils doesn't seem to like setup.py install_requires

### ISSUE THREAD

**Issue by phil-arista** [arista-eosplus/ztpserver#324]
Helped someone with an issue where their system only has distutils (and not setuptools).  So when they do setup.py build/install the dependencies never get installed via pip:

(Ubuntu 14.04 server)
```
root@server:/etc/ztpserver# python setup.py build
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
```

This comes from the setup.py using ``install_requires``.  Does distutils support this attribute?

REF: https://packaging.python.org/en/latest/requirements.html

**Comment by advornic** [comment]
From https://docs.python.org/2/distutils/setupscript.html:

"Dependencies on other Python modules and packages can be specified by supplying the requires keyword argument to setup(). The value must be a list of strings. Each string specifies a package that is required, and optionally what versions are sufficient."

**Comment by advornic** [comment]
sudo pip install setuptools --upgrade

will fix this. 

Not planning to support distutils moving forward.
