### ISSUE TITLE
Add min_version variable to the install_image action

### ISSUE THREAD

**Issue by urvishpanchal** [arista-eosplus/ztpserver#337]
With the current code, if the EOS version on the switch is a newer one compared to the one on the ZTP server definitions file, the OS will be downgraded. We should be able to avoid this by adding a min_version variable.

**Comment by jerearista** [comment]
There are a few possible solutions.  Would a flag in the action such as `downgrade: false` accomplish the desired results?  It would only replace an image if the specified image is newer than the `running` image.

**Comment by urvishpanchal** [comment]
Yes, that should work as well.
