### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by Casico** [arista-eosplus/ztpserver#379]
I have a fresh Ubuntu VM. 
Trying to install and getting the following error. 
I've tried pip and compiling it.
I am new to the Linux world and can admit it may be something that I'm doing wrong.

Collecting ztpserver
Using cached ztpserver-1.6.0.tar.gz
Preparing metdata (setup.py) ... error
error: subprocess-exited-wth-error
pyton setup.py egg_info did not run successfully

SyntazError: Missing parenthese in call to 'print'

**Comment by mharista** [comment]
@Casico 

Please respond here if this is still an issue.
